# Generated by Django 3.2.9 on 2022-01-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=30)),
                ('telephone_number', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ware')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('in_warehouse', models.CharField(max_length=30)),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ware')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('payed', models.PositiveIntegerField()),
                ('debt', models.PositiveIntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ware')),
            ],
        ),
    ]
