# Generated by Django 3.2.9 on 2022-01-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='debt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='payed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
