# Generated by Django 3.2.9 on 2022-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stats_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='debt',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
