# Generated by Django 3.2.9 on 2022-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stats_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_warehouse',
            field=models.PositiveIntegerField(max_length=30),
        ),
    ]
