# Generated by Django 3.2.9 on 2022-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_in_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='product_amount',
            field=models.PositiveIntegerField(max_length=30),
        ),
    ]
