# Generated by Django 4.0.1 on 2022-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220122_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(),
        ),
    ]
