# Generated by Django 3.2.9 on 2022-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='telephone_number',
            field=models.CharField(max_length=30),
        ),
    ]
